# Generated by Django 3.2.8 on 2021-10-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_availabilty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availabilty',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
