# Generated by Django 3.2.8 on 2021-10-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_availabilty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('3', 'ishlatilgan'), ('4', 'bepul'), ('2', 'yangi'), ('1', 'har qanday')], default='2', max_length=10),
        ),
    ]
