# Generated by Django 3.2.8 on 2021-11-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genders',
            field=models.CharField(choices=[('f', 'female'), ('m', 'male')], default='m', max_length=10),
        ),
    ]
