# Generated by Django 3.2.8 on 2021-10-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
